log:
 level: DEBUG
 output: ./output
http:
 port: 8080
 host: 0.0.0.0
models:
 sam_onnx_path: "infra/models/vit_h.onnx"
 dino_check_point_path: "/home/jerry/workbench/download/groundingdino_swinb_cogcoor.pth"
 dino_conf_file: "infra/config/grd.cfg.py"
 device: cpu
 